### PR TITLE
Missing 'kill-port' npm dependency on eos-extensions box

### PR DESCRIPTION
**Pull request by prcolaco**
Just a missing dependency needed while testing...

### CODE REVIEW

**Comment by NatPDeveloper** [comment]
Thank you for the PR, taking internally.  Not a required dependency, but perhaps something nice to have.

**Comment by prcolaco** [comment]
It was giving an error because I am not using any other box that has that dependency, and it is used on the test spec...

**Comment by NatPDeveloper** [comment]
Hm the `encrypted-key` test and the `zeus start localenv` seem to work ok me.

```
zeus unbox eos-extensions
zeus test
zeus start-localenv
zeus --version
2.0.3107
npm list -g kill-port
/home/ubuntu/.nvm/versions/node/v10.16.3/lib
└── (empty)
```

Which unit test are you dealing with?

I see that `02-eos-local-nodeos.js` requires `kill-port`, but that doesn't seem to be an issue for me out of the box so I'm curious why you're getting that error.

https://github.com/liquidapps-io/zeus-sdk/blob/master/boxes/groups/eos-sdk/eos-extensions/extensions/commands/start-localenv/02-eos-local-nodeos.js#L7

**Comment by NatPDeveloper** [comment]
PR accepted and merged to our pipeline!  Thank you!

**Pull request closed without merging**
